# Numpy intro

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int64')

In [9]:
data.nbytes

48

In [10]:
np.array([1, 2, 3], dtype=int)

array([1, 2, 3])

In [11]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data = np.array([1, 2, 3], dtype=float)
data

array([1., 2., 3.])

In [14]:
data.astype(int)

array([1, 2, 3])

In [15]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [16]:
(d1 + d2).dtype

dtype('complex128')

In [17]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [18]:
data = np.array([complex(1, 1), complex(2, 7), complex(3, 31)], dtype=complex)

In [19]:
data

array([1. +1.j, 2. +7.j, 3.+31.j])

In [20]:
data.real

array([1., 2., 3.])

In [21]:
data.imag

array([ 1.,  7., 31.])