# Reshaping and Resizing

In [2]:
import numpy as np

### Reshape example 1

In [3]:
data = np.array([[1, 2], [3, 4]])
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

### Reshape example 2

In [4]:
data.reshape(4)

array([1, 2, 3, 4])

### Flatten example

In [5]:
data.flatten()

array([1, 2, 3, 4])

In [6]:
data.flatten().shape

(4,)

### Column example with np.newaxis, then the corresponding new axes are added

In [8]:
data = np.arange(0, 5)
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

### Expand dims equivalent

In [11]:
np.expand_dims(data, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

### Row example with np.newaxis, then the corresponding new axes are added

In [12]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

### Expand dims equivalent

In [13]:
np.expand_dims(data, axis=0)

array([[0, 1, 2, 3, 4]])

## np.vstack and np.hstack <- vertical and horizontal stacks

## np.vstack concatenate rows

In [15]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [16]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## np.hstack concat vectors by adding to the end all of the elements

In [25]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [26]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

### Create column vector 1x5

In [27]:
vector = data[:, np.newaxis]
vector

array([[0],
       [1],
       [2],
       [3],
       [4]])

### And then concan by np.hstack 3 times this vector

In [28]:
np.hstack((vector, vector, vector))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])